# Generated by Django 5.2.17 on 2026-09-17 01:42

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domain", "0002_gamedatacoverage_reason_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetRevision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "committed_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("changed_game_ids", models.JSONField(blank=True, default=list)),
                ("invalidation_scopes", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="DataSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_type", models.CharField(max_length=60)),
                (
                    "parameter_fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                ("scope_key", models.CharField(max_length=200)),
                ("code_version", models.CharField(blank=True, max_length=100)),
                ("config_version", models.CharField(blank=True, max_length=100)),
                (
                    "started_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("finished_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempted_count", models.PositiveIntegerField(default=0)),
                ("succeeded_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnalyticsInvalidationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PROCESSED", "Processed")],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                (
                    "created_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasetrevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataSyncItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_kind", models.CharField(max_length=80)),
                ("target_key", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("checkpoint", models.CharField(blank=True, max_length=80)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                (
                    "updated_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "canonical_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasetrevision",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasyncrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="sync_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.datasyncitem",
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="sync_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.datasyncrun",
            ),
        ),
        migrations.AddField(
            model_name="datasyncrun",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ingestion.provider"
            ),
        ),
        migrations.CreateModel(
            name="ProviderAccessDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESEARCH_ONLY", "Research Only"),
                            (
                                "APPROVED_FOR_AUTOMATED_USE",
                                "Approved For Automated Use",
                            ),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=26,
                    ),
                ),
                (
                    "decision_reference",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "allowed_operation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("safe_note", models.TextField(blank=True)),
                (
                    "recorded_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="datasyncrun",
            name="access_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.provideraccessdecision",
            ),
        ),
        migrations.CreateModel(
            name="RawSourceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_kind", models.CharField(max_length=80)),
                ("external_target", models.CharField(max_length=200)),
                (
                    "request_fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                (
                    "retrieved_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                ("storage_key", models.CharField(max_length=240)),
                (
                    "provider_reported_at_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("UNPARSED", "Unparsed"),
                            ("PARSED", "Parsed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UNPARSED",
                        max_length=8,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="datasyncitem",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.rawsourcesnapshot",
            ),
        ),
        migrations.CreateModel(
            name="SourceRecordReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_kind", models.CharField(max_length=80)),
                (
                    "source_record_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("record_path", models.CharField(blank=True, max_length=200)),
                ("retrieved_at_utc", models.DateTimeField()),
                (
                    "provider_reported_at_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.rawsourcesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuarantineRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")
                        ],
                    ),
                ),
                ("candidate_kind", models.CharField(blank=True, max_length=80)),
                ("candidate_key", models.CharField(blank=True, max_length=200)),
                (
                    "created_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "resolution_state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("resolved_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.sourcerecordreference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FactSourceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_kind",
                    models.CharField(
                        choices=[
                            ("SEASON", "Season"),
                            ("TEAM", "Team"),
                            ("PLAYER", "Player"),
                            ("VENUE", "Venue"),
                            ("PLAYER_TEAM_AFFILIATION", "Player Team Affiliation"),
                            ("GAME", "Game"),
                            ("GAME_LIFECYCLE_EVENT", "Game Lifecycle Event"),
                            ("PLAYER_GAME_PARTICIPATION", "Player Game Participation"),
                            ("PLATE_APPEARANCE", "Plate Appearance"),
                            ("HOME_RUN_EVENT", "Home Run Event"),
                            ("GAME_DATA_COVERAGE", "Game Data Coverage"),
                        ],
                        max_length=30,
                    ),
                ),
                ("canonical_entity_id", models.UUIDField()),
                ("field_or_claim", models.CharField(blank=True, max_length=100)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("SUPPORTS", "Supports"),
                            ("CONFLICTS", "Conflicts"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("UNRESOLVED", "Unresolved"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.sourcerecordreference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("BLOCKING", "Blocking"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("target_kind", models.CharField(blank=True, max_length=80)),
                ("target_key", models.CharField(blank=True, max_length=200)),
                ("domain", models.CharField(blank=True, max_length=40)),
                (
                    "fingerprint",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "opened_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at_utc",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at_utc", models.DateTimeField(blank=True, null=True)),
                ("blocks_publication", models.BooleanField(default=False)),
                ("safe_detail", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.sourcerecordreference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageAssessmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("SCHEDULE", "Schedule"),
                            ("PARTICIPATION", "Participation"),
                            ("PLATE_APPEARANCES", "Plate Appearances"),
                            ("HR_EVENTS", "Hr Events"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("PARTIAL", "Partial"),
                            ("UNKNOWN", "Unknown"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOURCE_REQUEST_FAILED", "Source Request Failed"),
                            ("SOURCE_TRUNCATED", "Source Truncated"),
                            ("PARSE_FAILED", "Parse Failed"),
                            ("SCHEMA_DRIFT", "Schema Drift"),
                            ("FINALITY_UNKNOWN", "Finality Unknown"),
                            ("UNSUPPORTED_STATUS", "Unsupported Status"),
                            ("STATUS_CONFLICT", "Status Conflict"),
                            ("UNRESOLVED_PLAY", "Unresolved Play"),
                            ("NON_PA_PLAY_CLASSIFIED", "Non Pa Play Classified"),
                            ("MISSING_BATTER", "Missing Batter"),
                            ("DUPLICATE_ATBAT_INDEX", "Duplicate Atbat Index"),
                            ("BOX_SCORE_PA_MISMATCH", "Box Score Pa Mismatch"),
                            ("BOX_SCORE_HR_MISMATCH", "Box Score Hr Mismatch"),
                            ("HR_WITHOUT_PA", "Hr Without Pa"),
                            ("TEAM_ATTRIBUTION_CONFLICT", "Team Attribution Conflict"),
                            ("ORDER_UNRESOLVED", "Order Unresolved"),
                            (
                                "PARTICIPATION_POPULATION_UNVERIFIED",
                                "Participation Population Unverified",
                            ),
                            ("ACCESS_NOT_APPROVED", "Access Not Approved"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("assessed_at_utc", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.game"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasetrevision",
                    ),
                ),
                (
                    "sync_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasyncitem",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.sourcerecordreference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_kind", models.CharField(max_length=80)),
                ("external_target", models.CharField(max_length=200)),
                ("expires_at_utc", models.DateTimeField()),
                ("renewed_at_utc", models.DateTimeField()),
                (
                    "owner_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.datasyncrun",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_kind",
                    models.CharField(
                        choices=[
                            ("SEASON", "Season"),
                            ("TEAM", "Team"),
                            ("PLAYER", "Player"),
                            ("VENUE", "Venue"),
                            ("PLAYER_TEAM_AFFILIATION", "Player Team Affiliation"),
                            ("GAME", "Game"),
                            ("GAME_LIFECYCLE_EVENT", "Game Lifecycle Event"),
                            ("PLAYER_GAME_PARTICIPATION", "Player Game Participation"),
                            ("PLATE_APPEARANCE", "Plate Appearance"),
                            ("HOME_RUN_EVENT", "Home Run Event"),
                            ("GAME_DATA_COVERAGE", "Game Data Coverage"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_value", models.CharField(max_length=200)),
                ("canonical_entity_id", models.UUIDField()),
                (
                    "resolution_state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("AMBIGUOUS", "Ambiguous"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.provider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_kind", "canonical_entity_id"],
                        name="ingestion_e_entity__afa95e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolution_state", "ACTIVE")),
                        fields=("provider", "entity_kind", "external_value"),
                        name="unique_active_external_identifier",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="datasyncitem",
            constraint=models.UniqueConstraint(
                fields=("run", "target_kind", "target_key"), name="unique_run_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerecordreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_record_key__isnull", False),
                    models.Q(("source_record_key", ""), _negated=True),
                ),
                fields=("snapshot", "resource_kind", "source_record_key"),
                name="unique_snapshot_source_key",
            ),
        ),
        migrations.AddIndex(
            model_name="factsourcelink",
            index=models.Index(
                fields=["entity_kind", "canonical_entity_id"],
                name="ingestion_f_entity__2a6a18_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualityissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("severity", "BLOCKING"), _negated=True),
                    ("blocks_publication", True),
                    _connector="OR",
                ),
                name="blocking_issue_blocks_publication",
            ),
        ),
        migrations.AddIndex(
            model_name="coverageassessmenthistory",
            index=models.Index(
                fields=["game", "domain", "assessed_at_utc"],
                name="ingestion_c_game_id_3bf483_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetlease",
            constraint=models.UniqueConstraint(
                fields=("provider", "resource_kind", "external_target"),
                name="unique_target_lease",
            ),
        ),
    ]
