# Generated by Django 5.2.17 on 2026-09-17 01:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mlb_game_pk",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("POSTSEASON", "Postseason"),
                            ("SPRING", "Spring"),
                            ("ALL_STAR", "All Star"),
                            ("OTHER", "Other"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("official_date", models.DateField(blank=True, null=True)),
                ("scheduled_start_at_utc", models.DateTimeField(blank=True, null=True)),
                ("actual_start_at_utc", models.DateTimeField(blank=True, null=True)),
                ("completed_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("POSTPONED", "Postponed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUSPENDED", "Suspended"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OTHER", "Other"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                (
                    "finality",
                    models.CharField(
                        choices=[
                            ("FINAL", "Final"),
                            ("NOT_FINAL", "Not Final"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=9,
                    ),
                ),
                (
                    "scheduled_game_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mlb_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("given_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bats",
                    models.CharField(
                        choices=[
                            ("L", "Left"),
                            ("R", "Right"),
                            ("S", "Switch"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=7,
                    ),
                ),
                (
                    "throws",
                    models.CharField(
                        choices=[("L", "Left"), ("R", "Right"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        max_length=7,
                    ),
                ),
                (
                    "primary_position",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mlb_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("league", models.CharField(blank=True, max_length=80, null=True)),
                ("division", models.CharField(blank=True, max_length=80, null=True)),
                ("active_from_on", models.DateField(blank=True, null=True)),
                ("active_to_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mlb_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "timezone_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameLifecycleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_kind",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("POSTPONED", "Postponed"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("STARTED", "Started"),
                            ("SUSPENDED", "Suspended"),
                            ("RESUMED", "Resumed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("effective_at_utc", models.DateTimeField(blank=True, null=True)),
                ("recorded_at_utc", models.DateTimeField()),
                ("scheduled_start_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlateAppearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "half_inning",
                    models.CharField(
                        blank=True,
                        choices=[("TOP", "Top"), ("BOTTOM", "Bottom")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("game_pa_ordinal", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "outcome_category",
                    models.CharField(
                        choices=[
                            ("HOME_RUN", "Home Run"),
                            ("NON_HR", "Non Hr"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=8,
                    ),
                ),
                (
                    "batter_side_used",
                    models.CharField(
                        blank=True,
                        choices=[("L", "L"), ("R", "R")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "pitcher_hand_used",
                    models.CharField(
                        blank=True,
                        choices=[("L", "L"), ("R", "R")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.game"
                    ),
                ),
                (
                    "batter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batting_pas",
                        to="domain.player",
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pitching_pas",
                        to="domain.player",
                    ),
                ),
                (
                    "batting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batting_pas",
                        to="domain.team",
                    ),
                ),
                (
                    "fielding_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fielding_pas",
                        to="domain.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeRunEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plate_appearance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_run_event",
                        to="domain.plateappearance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="domain.season"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_games",
                to="domain.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_games",
                to="domain.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="domain.venue",
            ),
        ),
        migrations.CreateModel(
            name="GameDataCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("SCHEDULE", "Schedule"),
                            ("PARTICIPATION", "Participation"),
                            ("PLATE_APPEARANCES", "Plate Appearances"),
                            ("HR_EVENTS", "Hr Events"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("PARTIAL", "Partial"),
                            ("UNKNOWN", "Unknown"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="UNKNOWN",
                        max_length=11,
                    ),
                ),
                ("assessed_at_utc", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.game"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "domain"),
                        name="unique_current_game_domain_coverage",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerTeamAffiliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_from_date", models.DateField(blank=True, null=True)),
                (
                    "effective_to_date_exclusive",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "boundary_precision",
                    models.CharField(
                        choices=[("DATE", "Date"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        max_length=7,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.player"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="domain.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.team"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "effective_from_date"],
                        name="domain_play_player__c07b15_idx",
                    ),
                    models.Index(
                        fields=["team", "effective_from_date"],
                        name="domain_play_team_id_6874a6_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_from_date__isnull", True),
                            ("effective_to_date_exclusive__isnull", True),
                            (
                                "effective_from_date__lt",
                                models.F("effective_to_date_exclusive"),
                            ),
                            _connector="OR",
                        ),
                        name="affiliation_valid_known_interval",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerGameParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participation_state",
                    models.CharField(
                        choices=[
                            ("APPEARED", "Appeared"),
                            ("DID_NOT_APPEAR", "Did Not Appear"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=14,
                    ),
                ),
                ("started", models.BooleanField(blank=True, null=True)),
                (
                    "reported_pa_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "pa_coverage",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("PARTIAL", "Partial"),
                            ("UNKNOWN", "Unknown"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                        ],
                        default="UNKNOWN",
                        max_length=14,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="domain.team"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "game"], name="domain_play_player__9a607a_idx"
                    ),
                    models.Index(
                        fields=["team", "game"], name="domain_play_team_id_65b9cc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player", "team"),
                        name="unique_game_player_team",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="plateappearance",
            index=models.Index(
                fields=["batter", "game"], name="domain_plat_batter__0dd977_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plateappearance",
            index=models.Index(
                fields=["pitcher", "game"], name="domain_plat_pitcher_b4aecd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plateappearance",
            constraint=models.UniqueConstraint(
                fields=("game", "game_pa_ordinal"), name="unique_known_game_pa_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="plateappearance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("batting_team", models.F("fielding_team")), _negated=True
                ),
                name="pa_distinct_teams",
            ),
        ),
        migrations.AddConstraint(
            model_name="plateappearance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("game_pa_ordinal__isnull", True),
                    ("game_pa_ordinal__gt", 0),
                    _connector="OR",
                ),
                name="pa_positive_known_ordinal",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["season", "official_date", "game_type"],
                name="domain_game_season__b3d723_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["home_team", "official_date"],
                name="domain_game_home_te_128443_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["away_team", "official_date"],
                name="domain_game_away_te_c0ba71_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="game_distinct_teams",
            ),
        ),
    ]
