# Generated by Django 5.2.17 on 2026-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedatacoverage",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOURCE_REQUEST_FAILED", "Source Request Failed"),
                    ("SOURCE_TRUNCATED", "Source Truncated"),
                    ("PARSE_FAILED", "Parse Failed"),
                    ("SCHEMA_DRIFT", "Schema Drift"),
                    ("FINALITY_UNKNOWN", "Finality Unknown"),
                    ("UNSUPPORTED_STATUS", "Unsupported Status"),
                    ("STATUS_CONFLICT", "Status Conflict"),
                    ("UNRESOLVED_PLAY", "Unresolved Play"),
                    ("NON_PA_PLAY_CLASSIFIED", "Non Pa Play Classified"),
                    ("MISSING_BATTER", "Missing Batter"),
                    ("DUPLICATE_ATBAT_INDEX", "Duplicate Atbat Index"),
                    ("BOX_SCORE_PA_MISMATCH", "Box Score Pa Mismatch"),
                    ("BOX_SCORE_HR_MISMATCH", "Box Score Hr Mismatch"),
                    ("HR_WITHOUT_PA", "Hr Without Pa"),
                    ("TEAM_ATTRIBUTION_CONFLICT", "Team Attribution Conflict"),
                    ("ORDER_UNRESOLVED", "Order Unresolved"),
                    (
                        "PARTICIPATION_POPULATION_UNVERIFIED",
                        "Participation Population Unverified",
                    ),
                    ("ACCESS_NOT_APPROVED", "Access Not Approved"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
